/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

using System;
using System.Runtime.InteropServices;
    using System.Collections.Generic;

 /**
  * The list of FailedDevice objects contains an entry for every failed Leap Motion
  * hardware device connected to the client computer. FailedDevice objects report
  * the device pnpID string and reason for failure.
  *
  * Get the list of FailedDevice objects from Controller::failedDevices().
  *
  * @since 2.4.0
  */

public class FailedDeviceList : List<FailedDevice>{

   /**
    * Constructs an empty list.
    * @since 2.4.0
    */
  public FailedDeviceList() {
  }

   /**
    * Appends the contents of another FailedDeviceList to this one.
    * @since 2.4.0
    */
  public FailedDeviceList Append(FailedDeviceList other) {
    this.AddRange(other);
    return this;
  }

/**
    * Reports whether the list is empty.
    * @since 2.4.0
    */  public bool IsEmpty {
    get {
      return this.Count == 0;
    } 
  }

}

}
