/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

  /**
   * Reports whether the message is for
   * a severe failure, a recoverable warning, or a status change.
   * @since 2.4.0
   */
public enum MessageSeverity {
  MESSAGE_UNKNOWN = 0,
  MESSAGE_CRITICAL = 1,
  MESSAGE_WARNING = 2,
/** A verbose, informational message 
*/
  MESSAGE_INFORMATION = 3
}
  /**
   * Reports whether the message is for
   * a severe failure, a recoverable warning, or a status change.
   * @since 2.4.0
   */

}
